//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesManager.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<entidades> entidades { get; set; }
        public virtual DbSet<entidadesCampos> entidadesCampos { get; set; }
        public virtual DbSet<perfiles> perfiles { get; set; }
        public virtual DbSet<personas> personas { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tipoCampos> tipoCampos { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<menus> menus { get; set; }
        public virtual DbSet<perfilMenus> perfilMenus { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<estados> estados { get; set; }
        public virtual DbSet<municipios> municipios { get; set; }
        public virtual DbSet<paises> paises { get; set; }
    
        public virtual ObjectResult<string> spq_Desencriptar(string valor)
        {
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spq_Desencriptar", valorParameter);
        }
    
        public virtual ObjectResult<string> spq_Encriptar(string valor)
        {
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spq_Encriptar", valorParameter);
        }
    }
}
