//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesManager.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class entidadesCampos
    {
        public decimal entidadCampoId { get; set; }
        public int entidadId { get; set; }
        public int tipoCampoId { get; set; }
        public string id { get; set; }
        public string title { get; set; }
        public string @class { get; set; }
        public Nullable<int> minLength { get; set; }
        public Nullable<int> maxLength { get; set; }
        public string type { get; set; }
        public string placeholder { get; set; }
        public bool required { get; set; }
        public string cols { get; set; }
        public string onchange { get; set; }
        public string onfocus { get; set; }
        public string onclick { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual entidades entidades { get; set; }
        public virtual tipoCampos tipoCampos { get; set; }
    }
}
