//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesManager.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class menus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public menus()
        {
            this.perfilMenus = new HashSet<perfilMenus>();
        }
    
        public int id_menu { get; set; }
        public Nullable<int> id_menu_padre { get; set; }
        public string name { get; set; }
        public string menu { get; set; }
        public string url_mvc { get; set; }
        public bool openInNewWindow { get; set; }
        public string icon_ad { get; set; }
        public bool activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<perfilMenus> perfilMenus { get; set; }
    }
}
